POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
    "email": "grace.hopper@systers.xyz",
    "password": "123456"
}

POST http://localhost:8080/login HTTP/1.1
content-type: application/json

{
    "email": "waiter@systers.xyz",
    "password": "123456"
}

POST http://localhost:8080/users HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY5NTA4MDc0NCwiZXhwIjoxNjk1MDg0MzQ0LCJzdWIiOiIyIn0.5KNgws_HpydsuvLanLWYUjD5juhEaK-Wp7AlkboeFzc

{
    "email": "waiter@systers.xyz",
    "password": "123456",
    "role": "waiter"
}

POST http://localhost:8080/users HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY5NzQ2NTU4OCwiZXhwIjoxNjk3NDY5MTg4LCJzdWIiOiIyIn0.oPEXesmAfFlB2fRpPllAb_OH5LsgYyoPmbTqkjVWO90

{
    "email": "chef@systers.xyz",
    "password": "123456",
    "role": "chef"
}

POST http://localhost:8080/products HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY5NzEyNTU1MywiZXhwIjoxNjk3MTI5MTUzLCJzdWIiOiIyIn0.ILKM0JiW7l0BYm5llOaIPlx7bP570C4blC9akZaDMqI

{
    "name": "Agua BENDITA 500ml",
    "price": 500,
    "image": "https://raw.githubusercontent.com/ssinuco/burger-queen-api-mock/main/resources/images/water.png",
    "type": "Almuerzo"
}

GET http://localhost:8080/users HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY5NzQ2NTU4OCwiZXhwIjoxNjk3NDY5MTg4LCJzdWIiOiIyIn0.oPEXesmAfFlB2fRpPllAb_OH5LsgYyoPmbTqkjVWO90

GET http://localhost:8080/products HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY5NzYzNjQzOCwiZXhwIjoxNjk3NjQwMDM4LCJzdWIiOiIyIn0.hl3Ira6lu4VWE4avrPq2EPg7Omr8t3BkQGtF3oUkfwo

GET http://localhost:8080/orders HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY5NjQ1NTMyNCwiZXhwIjoxNjk2NDU4OTI0LCJzdWIiOiIyIn0.6xGCgrMY4hQRVXKrafERd8rvWUQsOrJM_ebiLVq4yr0


GET http://localhost:8080/orders?client=Ignacia HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY5NjAwNDkyNiwiZXhwIjoxNjk2MDA4NTI2LCJzdWIiOiIyIn0.N1J-NFeJZg-RiaAI4lK2X6-PsJnCZGzs_qOaojAHzc0

DELETE http://localhost:8080/orders/11 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY5NjI4MjM5MSwiZXhwIjoxNjk2Mjg1OTkxLCJzdWIiOiIyIn0.Een3Thtkw7ZNSa31ejwqlGK0LdgV50NRA6VuvXULlcs

PATCH http://localhost:8080/products/5 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY5NzU1ODc2MiwiZXhwIjoxNjk3NTYyMzYyLCJzdWIiOiIyIn0.BphTcJd2umzmvl0vAXw41LdmBCc8Yr62mn7IHen8Voo
{
    "status": "delivered",
    "dateProcessed": "2022-03-05 16:00"
}

PATCH http://localhost:8080/products/5 HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY5NzU1ODc2MiwiZXhwIjoxNjk3NTYyMzYyLCJzdWIiOiIyIn0.BphTcJd2umzmvl0vAXw41LdmBCc8Yr62mn7IHen8Voo

{
    "type": "Almuerzo"
}

POST http://localhost:8080/orders HTTP/1.1
content-type: application/json
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImdyYWNlLmhvcHBlckBzeXN0ZXJzLnh5eiIsImlhdCI6MTY5NTY1ODQ4MiwiZXhwIjoxNjk1NjYyMDgyLCJzdWIiOiIyIn0.0VAmjXXOguMNBJjLWSbSgyqIs8VfXFkTvp1ByIt34KM
{
    "client": "Harry Potter",
    "products": [
        {
            "qty": 1,
            "product": {
            "id": 1,
            "name": "Sandwich de jamón y queso",
            "price": 1000,
            "image": "https://github.com/Laboratoria/bootcamp/tree/main/projects/04-burger-queen-api/resources/images/sandwich.jpg",
            "type": "Desayuno",
            "dateEntry": "2022-03-05 15:14:10"
            }
        },
        {
            "qty": 1,
            "product": {
            "id": 2,
            "name": "Café americano",
            "price": 500,
            "image": "https://github.com/Laboratoria/bootcamp/tree/main/projects/04-burger-queen-api/resources/images/coffe.jpg",
            "type": "Desayuno",
            "dateEntry": "2022-03-05 15:14:10"
            }
        }
    ],
    "status": "pending",
    "dataEntry": "2022-03-05 15:00"
}